[package]
name = "RedPacket"
version = "1.0.0"
authors = ["Marvin"]

[addresses]
red_packet_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[dev-dependencies]
